export const SchemaName = {
  CART: 'cart',
  PRODUCT_CATEGORIES: 'product_category',
  CUSTOMER_ADDRESS: 'customer_address',
  CUSTOMERS: 'customer',
  EMPLOYEE: 'employee',
  ORDER_EXCHANGE: 'order_exchange',
  ORDER_HISTORY: 'order_history',
  ORDER_REFUND: 'order_refund',
  PERMISSION: 'permission',
  PRICE_BOOK: 'price_book',
  PRICE_BOOK_PRODUCT: 'price_book_product',
  PRODUCT_BOOKMARK: 'product_bookmark',
  PRODUCT_CATALOGUE: 'product_catalogue',
  PRODUCT_IMAGE: 'product_image',
  PRODUCT_VARIATION: 'product_variation',
  PRODUCT_MASTER: 'product_master',
  PRODUCT_PROMOTION: 'product_promotion',
  ROLE: 'role',
  PRODUCT_STUDIO_INVENTORY: 'product_studio_inventory',
  STUDIO: 'studio',
  STUDIO_TYPE: 'studio_type',
  ORDER: 'order',
  INVENTORY_HISTORY: 'studio_inventory_history',
  TAX_AUTH: 'tax_auth',
};
